// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(auth)/login/[[...rest]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login/[[...rest]]">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/login/[[...rest]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/data-hub/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/data-hub">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/data-hub/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/incentives/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/incentives">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/incentives/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/leads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leads">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/leads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/overview">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/sales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/sales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/telesales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/telesales">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/telesales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/data/cohorts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/data/cohorts">> = Specific
  const handler = {} as typeof import("../../src/app/api/data/cohorts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/data/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/data/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/data/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/data/incentives/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/data/incentives">> = Specific
  const handler = {} as typeof import("../../src/app/api/data/incentives/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/data/ingest/telesales-activity/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/data/ingest/telesales-activity">> = Specific
  const handler = {} as typeof import("../../src/app/api/data/ingest/telesales-activity/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/data/ingest/threshold/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/data/ingest/threshold">> = Specific
  const handler = {} as typeof import("../../src/app/api/data/ingest/threshold/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/data/leads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/data/leads">> = Specific
  const handler = {} as typeof import("../../src/app/api/data/leads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/data/mart-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/data/mart-status">> = Specific
  const handler = {} as typeof import("../../src/app/api/data/mart-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/data/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/data/overview">> = Specific
  const handler = {} as typeof import("../../src/app/api/data/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/data/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/data/products">> = Specific
  const handler = {} as typeof import("../../src/app/api/data/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/data/refresh-mart/chunk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/data/refresh-mart/chunk">> = Specific
  const handler = {} as typeof import("../../src/app/api/data/refresh-mart/chunk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/data/refresh-mart/finalize/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/data/refresh-mart/finalize">> = Specific
  const handler = {} as typeof import("../../src/app/api/data/refresh-mart/finalize/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/data/sales/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/data/sales">> = Specific
  const handler = {} as typeof import("../../src/app/api/data/sales/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/data/telesales/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/data/telesales">> = Specific
  const handler = {} as typeof import("../../src/app/api/data/telesales/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/data/upload/multipart/abort/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/data/upload/multipart/abort">> = Specific
  const handler = {} as typeof import("../../src/app/api/data/upload/multipart/abort/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/data/upload/multipart/complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/data/upload/multipart/complete">> = Specific
  const handler = {} as typeof import("../../src/app/api/data/upload/multipart/complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/data/upload/multipart/init/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/data/upload/multipart/init">> = Specific
  const handler = {} as typeof import("../../src/app/api/data/upload/multipart/init/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/data/upload/replay/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/data/upload/replay">> = Specific
  const handler = {} as typeof import("../../src/app/api/data/upload/replay/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webhooks/clerk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/clerk">> = Specific
  const handler = {} as typeof import("../../src/app/api/webhooks/clerk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
