import type { SchemaField, FileType } from '@/types'

export const FILE_TYPE_LABELS: Record<FileType, string> = {
  sales_online: 'Sales Order — Online (Makro Pro)',
  sales_offline: 'Sales Order — Offline (Makro Store)',
  product_list: 'Product List / SKU Reference',
  incentive: 'Incentive / Bonus Data',
  telesales_call_log: 'Telesales Call Log',
  lead_list: 'Lead List',
  target: 'Target / Budget',
}

export const SCHEMAS: Record<FileType, SchemaField[]> = {
  sales_online: [
    { key: 'order_id', label: 'Order ID', required: true, type: 'string' },
    { key: 'order_date', label: 'Order Date', required: true, type: 'date' },
    { key: 'customer_id', label: 'Customer ID', required: true, type: 'string' },
    { key: 'customer_name', label: 'Customer Name', required: false, type: 'string' },
    { key: 'product_sku', label: 'Product SKU', required: true, type: 'string' },
    { key: 'product_brand', label: 'Brand', required: false, type: 'string' },
    { key: 'product_category', label: 'Category', required: false, type: 'string' },
    { key: 'qty', label: 'Quantity', required: true, type: 'number' },
    { key: 'sales_amount', label: 'Sales Amount (THB)', required: true, type: 'number' },
    { key: 'mobile', label: 'Mobile', required: false, type: 'string' },
  ],
  sales_offline: [
    { key: 'order_id', label: 'Order ID', required: true, type: 'string' },
    { key: 'order_date', label: 'Order Date', required: true, type: 'date' },
    { key: 'customer_id', label: 'Customer ID', required: true, type: 'string' },
    { key: 'customer_name', label: 'Customer Name', required: false, type: 'string' },
    { key: 'product_sku', label: 'Product SKU', required: true, type: 'string' },
    { key: 'product_brand', label: 'Brand', required: false, type: 'string' },
    { key: 'product_category', label: 'Category', required: false, type: 'string' },
    { key: 'qty', label: 'Quantity', required: true, type: 'number' },
    { key: 'sales_amount', label: 'Sales Amount (THB)', required: true, type: 'number' },
    { key: 'store_id', label: 'Store ID', required: false, type: 'string' },
  ],
  telesales_call_log: [
    { key: 'customer_id', label: 'Customer ID', required: true, type: 'string' },
    { key: 'call_date', label: 'Call Date', required: true, type: 'date' },
    { key: 'call_status', label: 'Call Status', required: true, type: 'string' },
    { key: 'agent_name', label: 'Agent Name', required: true, type: 'string' },
    { key: 'agent_company', label: 'Agent Company', required: false, type: 'string' },
    { key: 'call_duration_sec', label: 'Duration (sec)', required: false, type: 'number' },
    { key: 'remark', label: 'Remark', required: false, type: 'string' },
  ],
  lead_list: [
    { key: 'customer_id', label: 'Customer ID', required: true, type: 'string' },
    { key: 'customer_name', label: 'Customer Name', required: false, type: 'string' },
    { key: 'mobile', label: 'Mobile', required: false, type: 'string' },
    { key: 'address', label: 'Address', required: false, type: 'string' },
    { key: 'segment', label: 'Segment', required: false, type: 'string' },
    { key: 'assigned_company', label: 'Assigned Telesales Company', required: false, type: 'string' },
    { key: 'assigned_date', label: 'Assigned Date', required: false, type: 'date' },
  ],
  product_list: [
    { key: 'product_sku', label: 'SKU', required: true, type: 'string' },
    { key: 'product_name', label: 'Product Name', required: true, type: 'string' },
    { key: 'product_brand', label: 'Brand', required: false, type: 'string' },
    { key: 'product_category', label: 'Category', required: false, type: 'string' },
    { key: 'unit_price', label: 'Unit Price (THB)', required: false, type: 'number' },
    { key: 'is_unilever', label: 'Is Unilever (true/false)', required: false, type: 'boolean' },
  ],
  incentive: [
    { key: 'period_start', label: 'Period Start', required: true, type: 'date' },
    { key: 'period_end', label: 'Period End', required: true, type: 'date' },
    { key: 'product_sku', label: 'SKU (blank = all)', required: false, type: 'string' },
    { key: 'product_brand', label: 'Brand (blank = all)', required: false, type: 'string' },
    { key: 'incentive_type', label: 'Incentive Type', required: false, type: 'string' },
    { key: 'incentive_value', label: 'Incentive Value (THB)', required: false, type: 'number' },
    { key: 'description', label: 'Description', required: false, type: 'string' },
  ],
  target: [
    { key: 'period_label', label: 'Period Label', required: true, type: 'string' },
    { key: 'period_start', label: 'Period Start', required: true, type: 'date' },
    { key: 'period_end', label: 'Period End', required: true, type: 'date' },
    { key: 'sales_target_thb', label: 'Sales Target (THB)', required: true, type: 'number' },
    { key: 'new_customer_target', label: 'New Customer Target', required: false, type: 'number' },
    { key: 'call_target', label: 'Call Target', required: false, type: 'number' },
    { key: 'channel', label: 'Channel (online/offline/all)', required: false, type: 'string' },
  ],
}
